name: generate animation

on:
  # Executar automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite executar manualmente o job a qualquer momento
  workflow_dispatch:
  
  # Executar a cada push na branch master
  push:
    branches:
      - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera um jogo de cobrinha a partir do gráfico de contribuições de um usuário do GitHub
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          # Substitua <seu_usuario_github> pelo seu nome de usuário do GitHub
          github_user_name: EnzoWarner
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # Personalização das cores
          color_snake: "#FF0000"  # Cor da cobra
          color_dots: "#00FF00, #0000FF, #FFFF00, #FF00FF"  # Cores dos blocos
          
      # Envia o conteúdo do diretório `dist` para um branch
      # O conteúdo estará disponível em https://raw.githubusercontent.com/<seu_usuario_github>/<seu_repositorio>/<branch_alvo>/<arquivo>
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Nome do branch de destino
          target_branch: output
          # Diretório com os arquivos a serem enviados para o branch de destino
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
