# Ação do GitHub para gerar um gráfico de contribuições com uma cobra comendo suas contribuições.
name: Generate Snake

# Controla quando a ação será executada.
on:
  schedule:
      # a cada 12 horas
    - cron: "0 */12 * * *"

  # Este comando nos permite executar a Ação automaticamente a partir da aba de Ações.
  workflow_dispatch:
  
  # Também executa em todo push na branch master
  push:
    branches:
    - main

# A sequência de execuções neste fluxo de trabalho:
jobs:
  # Este fluxo de trabalho contém um único job chamado "build"
  build:
    # O tipo de runner que o job será executado
    runs-on: ubuntu-latest

    # Etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
    
      - name: Gerar os arquivos da cobra em './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mostrar status da build
        run: git status

      - name: Enviar novos arquivos para a branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Atualizar animações da cobra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
